import Vue from 'vue'
import {
    Empty,
    Toast,
    ActionSheet,
    Sticky,
    Tab,
    Tabs,
    NavBar,
    Cell,
    List,
    NoticeBar,
    Swipe,
    SwipeItem,
    Icon,
    Search,
    Tabbar,
    TabbarItem,
    Col,
    Row,
    Form,
    Loading,
    Popup,
    Checkbox,
    Area,
    Field,
    Picker,
    Button,
    Lazyload,
    PullRefresh,
    Divider,
    Uploader,
    Image as VanImage
} from 'vant'
Vue.use(Empty);
Vue.use(Uploader);
Vue.use(Toast);
Vue.use(ActionSheet);
Vue.use(VanImage);
Vue.use(Sticky);
Vue.use(Divider);
Vue.use(SwipeItem);
Vue.use(NavBar);
Vue.use(PullRefresh);
Vue.use(Cell);
Vue.use(List);
Vue.use(Swipe);
Vue.use(Lazyload);
Vue.use(Search);
Vue.use(Icon);
Vue.use(Form);
Vue.use(Col);
Vue.use(Row);
Vue.use(Popup);
Vue.use(Checkbox);
Vue.use(Area);
Vue.use(Field);
Vue.use(Picker);
Vue.use(Button);
Vue.use(Loading);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(NoticeBar);
Vue.use(Tab);
Vue.use(Tabs);